### ISSUE TITLE
Hub not reachable locally

### ISSUE THREAD

**Issue by randot** [sibartlett/homebridge-wink3#31] opened 2017-08-07 03:07 UTC
I get the following messages at the end of the Homebridge launch. It looks like it was able to talk to the hub, but then timed out. Is there a way I solve that?

`[2017-8-7 03:04:03] [Wink] Authenticated with local Wink hub (XXX.XXX.X.X)
[2017-8-7 03:04:07] [Wink] Wink hub (XXX.XXX.X.X) is not reachable locally. Error: ESOCKETTIMEDOUT
`

**Comment by smartymanav** [comment] 2017-08-09 22:43
I am getting the same error...

**Comment by dcgrove** [comment] 2017-08-10 13:11
I am getting this error too.

[8/10/2017, 8:11:01 AM] [Wink3] Wink hub (192.168.1.147) is not reachable locally. Error: ESOCKETTIMEDOUT

**Comment by sibartlett** [comment] 2017-08-10 13:34
The plugin will still continue to function after logging this warning. It's just not able to send commands directly to the hub, instead it'll send commands to the Wink API.

@randot I see you have two log messages, did they both have the same I.P. or they referring to 2 different hubs?

I'll publish a new version that does a bit more logging, so it's easier to follow.

**Comment by sibartlett** [comment] 2017-08-10 14:01
I've published a new version (1.5.1), which has improved logging - which will hopefully give a better insight into what's happening.

**Comment by dcgrove** [comment] 2017-08-10 14:06
So for us linux neophytes, how do we update to the new version? I have run this command but it is not upgrading.

`sudo npm update -g homebridge-wink3`

**Comment by dcgrove** [comment] 2017-08-10 14:11
I am upgraded to 1.51.  Where are the logs located?

**Comment by sibartlett** [comment] 2017-08-10 14:14
@dcgrove it's the same log output you got the previous error from, stdout I assume?

**Comment by dcgrove** [comment] 2017-08-10 14:17
Let me preface by stating I am a complete linux neophyte basically googling my way through using this.  I copied the error message above directly from the terminal window where homebridge runs.

**Comment by sibartlett** [comment] 2017-08-10 14:27
It's not much, but the logging should look like one of the following examples.

There are two additions:
* `Checking if Wink hub (X) is reachable...`
* `Will continue without local control for Wink hub (X)` - which is there to reassure users that the plugin will still work, just without local control.

**Local hub reachable:**

    [8/10/2017, 9:56:47 AM] Homebridge is running on port 51826.
    [8/10/2017, 9:56:47 AM] [Wink] Refreshing devices...
    [8/10/2017, 9:56:51 AM] [Wink] Checking if Wink hub (192.168.1.3) is reachable...
    [8/10/2017, 9:56:51 AM] [Wink] Devices refreshed
    [8/10/2017, 9:56:51 AM] [Wink] Wink hub (192.168.1.3) is reachable locally
    [8/10/2017, 9:56:52 AM] [Wink] Authenticated with local Wink hub (192.168.1.3)

    
**Local hub NOT reachable:**

    [8/10/2017, 9:56:47 AM] Homebridge is running on port 51826.
    [8/10/2017, 9:56:47 AM] [Wink] Refreshing devices...
    [8/10/2017, 9:56:51 AM] [Wink] Checking if Wink hub (192.168.1.3) is reachable...
    [8/10/2017, 9:56:51 AM] [Wink] Devices refreshed
    [8/10/2017, 9:56:51 AM] [Wink] Wink hub (192.168.1.147) is not reachable locally. Error: ESOCKETTIMEDOUT
    [8/10/2017, 9:56:51 AM] [Wink] Will continue without local control for Wink hub (192.168.1.3)

@dcgrove the output in the terminal window is often referred to as stdout, so the terminal window is exactly the right place to be looking.

**Comment by randot** [comment] 2017-08-10 17:48
@sibartlett I hadn't noticed at the time, but they actually were two different IPs, and I do have both a Hub 2 and a Hub 1 running, so it must be saying the Hub 1 is not reachable locally. 

Thanks!

**Comment by sibartlett** [comment] 2017-08-10 17:50
@randot hmm, sometimes restarting the Hub 1 and then restarting homebridge fixes the issue.

**Comment by randot** [comment] 2017-08-10 18:08
Ok, I’ll try that. Do you know if there’s a way to tell whether that message is coming from the Hub 1 or 2? Not sure how to find their IPs. If it’s Hub 1, there’s not much on it I care about for HomeKit. But I do want to take advantage of the local control on Hub 2 if I can. Thanks!

**Comment by dcgrove** [comment] 2017-08-10 18:09
@randot can you not look at the DHCP assingments in your router to identify the hubs IP address?

**Comment by sibartlett** [comment] 2017-08-10 18:13
I can update the logging again, to output the actual name of the hub.

**Comment by randot** [comment] 2017-08-10 18:32
I didn’t think I could with Airport Utility, but I just found a hidden option that reveals enough info. 

Simon, it turns out it is the Hub 2 that can’t connect locally. I’ll try restarting that and then Homebridge later today.

Thanks.

**Comment by sibartlett** [comment] 2017-08-10 18:48
I've published a new version (1.5.2) which includes the name of the hub in the log messages.

**Comment by dcgrove** [comment] 2017-08-10 20:13
is there a command I can run to see which version of the plugin is running?

**Comment by sibartlett** [comment] 2017-08-10 20:15
@dcgrove this will list all the packages (and their versions) you've installed globally:

    npm list -g --depth=0

**Comment by bassrock** [comment] 2017-08-15 05:34
I am getting the following error:

```
Could not authenticate with local hub (Living Room Wink Relay, 192.168.2.221) { StatusCodeError: 429 - {"data":null,"errors":["You have been throttled. Please try again later."],"pagination":{}}
```

However I am the only person using my api key..

**Comment by sibartlett** [comment] 2017-08-15 16:32
@bassrock first time I've seen that error message!

The plugin should still work if it can't authenticate with a local hub, it will fallback to the Wink API instead of local control. However, I am curious if that is the case for you, or if all your API requests are being throttled?

Also I just published a new version (1.5.6). It'll ignore hubs if they're not associated to any homebridge accessories, but I doubt that'll help in your case.

**Comment by bassrock** [comment] 2017-08-16 02:54
@sibartlett yea here it is in more detail:

```
Could not authenticate with local hub (Hub, 192.168.2.48) { StatusCodeError: 429 - {"data":null,"errors":["You have been throttled. Please try again later."],"pagination":{}}
8/15/2017 7:50:26 PM    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/errors.js:32:15)
8/15/2017 7:50:26 PM    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:104:33)
8/15/2017 7:50:26 PM    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:46:31)
8/15/2017 7:50:26 PM    at Request.self.callback (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request/request.js:188:22)
8/15/2017 7:50:26 PM    at emitTwo (events.js:125:13)
8/15/2017 7:50:26 PM    at Request.emit (events.js:213:7)
8/15/2017 7:50:26 PM    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request/request.js:1171:10)
8/15/2017 7:50:26 PM    at emitOne (events.js:115:13)
8/15/2017 7:50:26 PM    at Request.emit (events.js:210:7)
8/15/2017 7:50:26 PM    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request/request.js:1091:12)
8/15/2017 7:50:26 PM    at Object.onceWrapper (events.js:314:30)
8/15/2017 7:50:26 PM    at emitNone (events.js:110:20)
8/15/2017 7:50:26 PM    at IncomingMessage.emit (events.js:207:7)
8/15/2017 7:50:26 PM    at endReadableNT (_stream_readable.js:1045:12)
8/15/2017 7:50:26 PM    at _combinedTickCallback (internal/process/next_tick.js:138:11)
8/15/2017 7:50:26 PM    at process._tickCallback (internal/process/next_tick.js:180:9)
8/15/2017 7:50:26 PM  name: 'StatusCodeError',
8/15/2017 7:50:26 PM  statusCode: 429,
8/15/2017 7:50:26 PM  message: '429 - {"data":null,"errors":["You have been throttled. Please try again later."],"pagination":{}}',
8/15/2017 7:50:26 PM  error:
8/15/2017 7:50:26 PM   { data: null,
8/15/2017 7:50:26 PM     errors: [ 'You have been throttled. Please try again later.' ],
8/15/2017 7:50:26 PM     pagination: {} },
8/15/2017 7:50:26 PM  options:
8/15/2017 7:50:26 PM   { baseUrl: 'https://api.wink.com',
8/15/2017 7:50:26 PM     strictSSL: true,
8/15/2017 7:50:26 PM     json: true,
8/15/2017 7:50:26 PM     method: 'POST',
8/15/2017 7:50:26 PM     uri: '/oauth2/token',
8/15/2017 7:50:26 PM     body:
8/15/2017 7:50:26 PM      { local_control_id: 'b588b292-9e75-4006-b9f4-4017245238ce',
8/15/2017 7:50:26 PM        scope: 'local_control',
8/15/2017 7:50:26 PM        grant_type: 'refresh_token',
8/15/2017 7:50:26 PM        refresh_token: 'A9rvVt4f7GoO8ZdTK-LTre9ff99up8Sd',
8/15/2017 7:50:26 PM        client_id: 'PSOUsz9KRKSMOzh-P_mprcoHyJXEGTLU',
8/15/2017 7:50:26 PM        client_secret: 'n3JDagDMfN2MZZA12iuwbZphRHQQ4S9w' },
8/15/2017 7:50:26 PM     headers: { 'User-Agent': 'Manufacturer/Apple-iPhone8_1 iOS/10.3.1 WinkiOS/5.8.0.27-production-release (Scale/2.00)' },
8/15/2017 7:50:26 PM     callback: [Function: RP$callback],
8/15/2017 7:50:26 PM     transform: undefined,
8/15/2017 7:50:26 PM     simple: true,
8/15/2017 7:50:26 PM     resolveWithFullResponse: false,
8/15/2017 7:50:26 PM     transform2xxOnly: false },
8/15/2017 7:50:26 PM  response:
8/15/2017 7:50:26 PM   IncomingMessage {
8/15/2017 7:50:26 PM     _readableState:
8/15/2017 7:50:26 PM      ReadableState {
8/15/2017 7:50:26 PM        objectMode: false,
8/15/2017 7:50:26 PM        highWaterMark: 16384,
8/15/2017 7:50:26 PM        buffer: [Object],
8/15/2017 7:50:26 PM        length: 0,
8/15/2017 7:50:26 PM        pipes: null,
8/15/2017 7:50:26 PM        pipesCount: 0,
8/15/2017 7:50:26 PM        flowing: true,
8/15/2017 7:50:26 PM        ended: true,
8/15/2017 7:50:26 PM        endEmitted: true,
8/15/2017 7:50:26 PM        reading: false,
8/15/2017 7:50:26 PM        sync: true,
8/15/2017 7:50:26 PM        needReadable: false,
8/15/2017 7:50:26 PM        emittedReadable: false,
8/15/2017 7:50:26 PM        readableListening: false,
8/15/2017 7:50:26 PM        resumeScheduled: false,
8/15/2017 7:50:26 PM        destroyed: false,
8/15/2017 7:50:26 PM        defaultEncoding: 'utf8',
8/15/2017 7:50:26 PM        awaitDrain: 0,
8/15/2017 7:50:26 PM        readingMore: false,
8/15/2017 7:50:26 PM        decoder: null,
8/15/2017 7:50:26 PM        encoding: null },
8/15/2017 7:50:26 PM     readable: false,
8/15/2017 7:50:26 PM     domain: null,
8/15/2017 7:50:26 PM     _events:
8/15/2017 7:50:26 PM      { end: [Array],
8/15/2017 7:50:26 PM        close: [Array],
8/15/2017 7:50:26 PM        data: [Function],
8/15/2017 7:50:26 PM        error: [Function] },
8/15/2017 7:50:26 PM     _eventsCount: 4,
8/15/2017 7:50:26 PM     _maxListeners: undefined,
8/15/2017 7:50:26 PM     socket:
8/15/2017 7:50:26 PM      TLSSocket {
8/15/2017 7:50:26 PM        _tlsOptions: [Object],
8/15/2017 7:50:26 PM        _secureEstablished: true,
8/15/2017 7:50:26 PM        _securePending: false,
8/15/2017 7:50:26 PM        _newSessionPending: false,
8/15/2017 7:50:26 PM        _controlReleased: true,
8/15/2017 7:50:26 PM        _SNICallback: null,
8/15/2017 7:50:26 PM        servername: null,
8/15/2017 7:50:26 PM        npnProtocol: false,
8/15/2017 7:50:26 PM        alpnProtocol: false,
8/15/2017 7:50:26 PM        authorized: true,
8/15/2017 7:50:26 PM        authorizationError: null,
8/15/2017 7:50:26 PM        encrypted: true,
8/15/2017 7:50:26 PM        _events: [Object],
8/15/2017 7:50:26 PM        _eventsCount: 9,
8/15/2017 7:50:26 PM        connecting: false,
8/15/2017 7:50:26 PM        _hadError: false,
8/15/2017 7:50:26 PM        _handle: null,
8/15/2017 7:50:26 PM        _parent: null,
8/15/2017 7:50:26 PM        _host: 'api.wink.com',
8/15/2017 7:50:26 PM        _readableState: [Object],
8/15/2017 7:50:26 PM        readable: false,
8/15/2017 7:50:26 PM        domain: null,
8/15/2017 7:50:26 PM        _maxListeners: undefined,
8/15/2017 7:50:26 PM        _writableState: [Object],
8/15/2017 7:50:26 PM        writable: false,
8/15/2017 7:50:26 PM        allowHalfOpen: false,
8/15/2017 7:50:26 PM        _bytesDispatched: 512,
8/15/2017 7:50:26 PM        _sockname: null,
8/15/2017 7:50:26 PM        _pendingData: null,
8/15/2017 7:50:26 PM        _pendingEncoding: '',
8/15/2017 7:50:26 PM        server: undefined,
8/15/2017 7:50:26 PM        _server: null,
8/15/2017 7:50:26 PM        ssl: null,
8/15/2017 7:50:26 PM        _requestCert: true,
8/15/2017 7:50:26 PM        _rejectUnauthorized: true,
8/15/2017 7:50:26 PM        parser: null,
8/15/2017 7:50:26 PM        _httpMessage: [Object],
8/15/2017 7:50:26 PM        read: [Function],
8/15/2017 7:50:26 PM        _consuming: true,
8/15/2017 7:50:26 PM        _idleNext: null,
8/15/2017 7:50:26 PM        _idlePrev: null,
8/15/2017 7:50:26 PM        _idleTimeout: -1,
8/15/2017 7:50:26 PM        [Symbol(asyncId)]: 1967,
8/15/2017 7:50:26 PM        [Symbol(bytesRead)]: 521 },
8/15/2017 7:50:26 PM     connection:
8/15/2017 7:50:26 PM      TLSSocket {
8/15/2017 7:50:26 PM        _tlsOptions: [Object],
8/15/2017 7:50:26 PM        _secureEstablished: true,
8/15/2017 7:50:26 PM        _securePending: false,
8/15/2017 7:50:26 PM        _newSessionPending: false,
8/15/2017 7:50:26 PM        _controlReleased: true,
8/15/2017 7:50:26 PM        _SNICallback: null,
8/15/2017 7:50:26 PM        servername: null,
8/15/2017 7:50:26 PM        npnProtocol: false,
8/15/2017 7:50:26 PM        alpnProtocol: false,
8/15/2017 7:50:26 PM        authorized: true,
8/15/2017 7:50:26 PM        authorizationError: null,
8/15/2017 7:50:26 PM        encrypted: true,
8/15/2017 7:50:26 PM        _events: [Object],
8/15/2017 7:50:26 PM        _eventsCount: 9,
8/15/2017 7:50:26 PM        connecting: false,
8/15/2017 7:50:26 PM        _hadError: false,
8/15/2017 7:50:26 PM        _handle: null,
8/15/2017 7:50:26 PM        _parent: null,
8/15/2017 7:50:26 PM        _host: 'api.wink.com',
8/15/2017 7:50:26 PM        _readableState: [Object],
8/15/2017 7:50:26 PM        readable: false,
8/15/2017 7:50:26 PM        domain: null,
8/15/2017 7:50:26 PM        _maxListeners: undefined,
8/15/2017 7:50:26 PM        _writableState: [Object],
8/15/2017 7:50:26 PM        writable: false,
8/15/2017 7:50:26 PM        allowHalfOpen: false,
8/15/2017 7:50:26 PM        _bytesDispatched: 512,
8/15/2017 7:50:26 PM        _sockname: null,
8/15/2017 7:50:26 PM        _pendingData: null,
8/15/2017 7:50:26 PM        _pendingEncoding: '',
8/15/2017 7:50:26 PM        server: undefined,
8/15/2017 7:50:26 PM        _server: null,
8/15/2017 7:50:26 PM        ssl: null,
8/15/2017 7:50:26 PM        _requestCert: true,
8/15/2017 7:50:26 PM        _rejectUnauthorized: true,
8/15/2017 7:50:26 PM        parser: null,
8/15/2017 7:50:26 PM        _httpMessage: [Object],
8/15/2017 7:50:26 PM        read: [Function],
8/15/2017 7:50:26 PM        _consuming: true,
8/15/2017 7:50:26 PM        _idleNext: null,
8/15/2017 7:50:26 PM        _idlePrev: null,
8/15/2017 7:50:26 PM        _idleTimeout: -1,
8/15/2017 7:50:26 PM        [Symbol(asyncId)]: 1967,
8/15/2017 7:50:26 PM        [Symbol(bytesRead)]: 521 },
8/15/2017 7:50:26 PM     httpVersionMajor: 1,
8/15/2017 7:50:26 PM     httpVersionMinor: 1,
8/15/2017 7:50:26 PM     httpVersion: '1.1',
8/15/2017 7:50:26 PM     complete: true,
8/15/2017 7:50:26 PM     headers:
8/15/2017 7:50:26 PM      { 'cache-control': 'no-cache',
8/15/2017 7:50:26 PM        'content-type': 'application/json',
8/15/2017 7:50:26 PM        'retry-after': '15',
8/15/2017 7:50:26 PM        'strict-transport-security': 'max-age=31536000',
8/15/2017 7:50:26 PM        via: '1.1 spaces-router (e08eb2083458)',
8/15/2017 7:50:26 PM        'x-ratelimit-limit': '5',
8/15/2017 7:50:26 PM        'x-ratelimit-remaining': '0',
8/15/2017 7:50:26 PM        'x-ratelimit-reset': '2017-08-16T02:50:40Z',
8/15/2017 7:50:26 PM        'x-request-id': '03f5fa9f-f57b-7a3f-dc51-41d84ed97ed4',
8/15/2017 7:50:26 PM        'x-runtime': '0.008653',
8/15/2017 7:50:26 PM        date: 'Wed, 16 Aug 2017 02:50:25 GMT',
8/15/2017 7:50:26 PM        'content-length': '91',
8/15/2017 7:50:26 PM        connection: 'close' },
8/15/2017 7:50:26 PM     rawHeaders:
8/15/2017 7:50:26 PM      [ 'Cache-Control',
8/15/2017 7:50:26 PM        'no-cache',
8/15/2017 7:50:26 PM        'Content-Type',
8/15/2017 7:50:26 PM        'application/json',
8/15/2017 7:50:26 PM        'Retry-After',
8/15/2017 7:50:26 PM        '15',
8/15/2017 7:50:26 PM        'Strict-Transport-Security',
8/15/2017 7:50:26 PM        'max-age=31536000',
8/15/2017 7:50:26 PM        'Via',
8/15/2017 7:50:26 PM        '1.1 spaces-router (e08eb2083458)',
8/15/2017 7:50:26 PM        'X-Ratelimit-Limit',
8/15/2017 7:50:26 PM        '5',
8/15/2017 7:50:26 PM        'X-Ratelimit-Remaining',
8/15/2017 7:50:26 PM        '0',
8/15/2017 7:50:26 PM        'X-Ratelimit-Reset',
8/15/2017 7:50:26 PM        '2017-08-16T02:50:40Z',
8/15/2017 7:50:26 PM        'X-Request-Id',
8/15/2017 7:50:26 PM        '03f5fa9f-f57b-7a3f-dc51-41d84ed97ed4',
8/15/2017 7:50:26 PM        'X-Runtime',
8/15/2017 7:50:26 PM        '0.008653',
8/15/2017 7:50:26 PM        'Date',
8/15/2017 7:50:26 PM        'Wed, 16 Aug 2017 02:50:25 GMT',
8/15/2017 7:50:26 PM        'Content-Length',
8/15/2017 7:50:26 PM        '91',
8/15/2017 7:50:26 PM        'Connection',
8/15/2017 7:50:26 PM        'close' ],
8/15/2017 7:50:26 PM     trailers: {},
8/15/2017 7:50:26 PM     rawTrailers: [],
8/15/2017 7:50:26 PM     upgrade: false,
8/15/2017 7:50:26 PM     url: '',
8/15/2017 7:50:26 PM     method: null,
8/15/2017 7:50:26 PM     statusCode: 429,
8/15/2017 7:50:26 PM     statusMessage: 'Too Many Requests',
8/15/2017 7:50:26 PM     client:
8/15/2017 7:50:26 PM      TLSSocket {
8/15/2017 7:50:26 PM        _tlsOptions: [Object],
8/15/2017 7:50:26 PM        _secureEstablished: true,
8/15/2017 7:50:26 PM        _securePending: false,
8/15/2017 7:50:26 PM        _newSessionPending: false,
8/15/2017 7:50:26 PM        _controlReleased: true,
8/15/2017 7:50:26 PM        _SNICallback: null,
8/15/2017 7:50:26 PM        servername: null,
8/15/2017 7:50:26 PM        npnProtocol: false,
8/15/2017 7:50:26 PM        alpnProtocol: false,
8/15/2017 7:50:26 PM        authorized: true,
8/15/2017 7:50:26 PM        authorizationError: null,
8/15/2017 7:50:26 PM        encrypted: true,
8/15/2017 7:50:26 PM        _events: [Object],
8/15/2017 7:50:26 PM        _eventsCount: 9,
8/15/2017 7:50:26 PM        connecting: false,
8/15/2017 7:50:26 PM        _hadError: false,
8/15/2017 7:50:26 PM        _handle: null,
8/15/2017 7:50:26 PM        _parent: null,
8/15/2017 7:50:26 PM        _host: 'api.wink.com',
8/15/2017 7:50:26 PM        _readableState: [Object],
8/15/2017 7:50:26 PM        readable: false,
8/15/2017 7:50:26 PM        domain: null,
8/15/2017 7:50:26 PM        _maxListeners: undefined,
8/15/2017 7:50:26 PM        _writableState: [Object],
8/15/2017 7:50:26 PM        writable: false,
8/15/2017 7:50:26 PM        allowHalfOpen: false,
8/15/2017 7:50:26 PM        _bytesDispatched: 512,
8/15/2017 7:50:26 PM        _sockname: null,
8/15/2017 7:50:26 PM        _pendingData: null,
8/15/2017 7:50:26 PM        _pendingEncoding: '',
8/15/2017 7:50:26 PM        server: undefined,
8/15/2017 7:50:26 PM        _server: null,
8/15/2017 7:50:26 PM        ssl: null,
8/15/2017 7:50:26 PM        _requestCert: true,
8/15/2017 7:50:26 PM        _rejectUnauthorized: true,
8/15/2017 7:50:26 PM        parser: null,
8/15/2017 7:50:26 PM        _httpMessage: [Object],
8/15/2017 7:50:26 PM        read: [Function],
8/15/2017 7:50:26 PM        _consuming: true,
8/15/2017 7:50:26 PM        _idleNext: null,
8/15/2017 7:50:26 PM        _idlePrev: null,
8/15/2017 7:50:26 PM        _idleTimeout: -1,
8/15/2017 7:50:26 PM        [Symbol(asyncId)]: 1967,
8/15/2017 7:50:26 PM        [Symbol(bytesRead)]: 521 },
8/15/2017 7:50:26 PM     _consuming: true,
8/15/2017 7:50:26 PM     _dumped: false,
8/15/2017 7:50:26 PM     req:
8/15/2017 7:50:26 PM      ClientRequest {
8/15/2017 7:50:26 PM        domain: null,
8/15/2017 7:50:26 PM        _events: [Object],
8/15/2017 7:50:26 PM        _eventsCount: 5,
8/15/2017 7:50:26 PM        _maxListeners: undefined,
8/15/2017 7:50:26 PM        output: [],
8/15/2017 7:50:26 PM        outputEncodings: [],
8/15/2017 7:50:26 PM        outputCallbacks: [],
8/15/2017 7:50:26 PM        outputSize: 0,
8/15/2017 7:50:26 PM        writable: false,
8/15/2017 7:50:26 PM        _last: true,
8/15/2017 7:50:26 PM        upgrading: false,
8/15/2017 7:50:26 PM        chunkedEncoding: false,
8/15/2017 7:50:26 PM        shouldKeepAlive: false,
8/15/2017 7:50:26 PM        useChunkedEncodingByDefault: true,
8/15/2017 7:50:26 PM        sendDate: false,
8/15/2017 7:50:26 PM        _removedConnection: false,
8/15/2017 7:50:26 PM        _removedContLen: false,
8/15/2017 7:50:26 PM        _removedTE: false,
8/15/2017 7:50:26 PM        _contentLength: null,
8/15/2017 7:50:26 PM        _hasBody: true,
8/15/2017 7:50:26 PM        _trailer: '',
8/15/2017 7:50:26 PM        finished: true,
8/15/2017 7:50:26 PM        _headerSent: true,
8/15/2017 7:50:26 PM        socket: [Object],
8/15/2017 7:50:26 PM        connection: [Object],
8/15/2017 7:50:26 PM        _header: 'POST /oauth2/token HTTP/1.1\r\nUser-Agent: Manufacturer/Apple-iPhone8_1 iOS/10.3.1 WinkiOS/5.8.0.27-production-release (Scale/2.00)\r\nhost: api.wink.com\r\naccept: application/json\r\ncontent-type: application/json\r\ncontent-length: 261\r\nConnection: close\r\n\r\n',
8/15/2017 7:50:26 PM        _onPendingData: [Function: noopPendingOutput],
8/15/2017 7:50:26 PM        agent: [Object],
8/15/2017 7:50:26 PM        socketPath: undefined,
8/15/2017 7:50:26 PM        timeout: undefined,
8/15/2017 7:50:26 PM        method: 'POST',
8/15/2017 7:50:26 PM        path: '/oauth2/token',
8/15/2017 7:50:26 PM        _ended: true,
8/15/2017 7:50:26 PM        res: [Circular],
8/15/2017 7:50:26 PM        aborted: undefined,
8/15/2017 7:50:26 PM        timeoutCb: null,
8/15/2017 7:50:26 PM        upgradeOrConnect: false,
8/15/2017 7:50:26 PM        parser: null,
8/15/2017 7:50:26 PM        maxHeadersCount: null,
8/15/2017 7:50:26 PM        [Symbol(outHeadersKey)]: [Object] },
8/15/2017 7:50:26 PM     request:
8/15/2017 7:50:26 PM      Request {
8/15/2017 7:50:26 PM        domain: null,
8/15/2017 7:50:26 PM        _events: [Object],
8/15/2017 7:50:26 PM        _eventsCount: 5,
8/15/2017 7:50:26 PM        _maxListeners: undefined,
8/15/2017 7:50:26 PM        strictSSL: true,
8/15/2017 7:50:26 PM        method: 'POST',
8/15/2017 7:50:26 PM        uri: [Object],
8/15/2017 7:50:26 PM        body: '{"local_control_id":"b588b292-9e75-4006-b9f4-4017245238ce","scope":"local_control","grant_type":"refresh_token","refresh_token":"A9rvVt4f7GoO8ZdTK-LTre9ff99up8Sd","client_id":"PSOUsz9KRKSMOzh-P_mprcoHyJXEGTLU","client_secret":"n3JDagDMfN2MZZA12iuwbZphRHQQ4S9w"}',
8/15/2017 7:50:26 PM        headers: [Object],
8/15/2017 7:50:26 PM        readable: true,
8/15/2017 7:50:26 PM        writable: true,
8/15/2017 7:50:26 PM        explicitMethod: true,
8/15/2017 7:50:26 PM        _qs: [Object],
8/15/2017 7:50:26 PM        _auth: [Object],
8/15/2017 7:50:26 PM        _oauth: [Object],
8/15/2017 7:50:26 PM        _multipart: [Object],
8/15/2017 7:50:26 PM        _redirect: [Object],
8/15/2017 7:50:26 PM        _tunnel: [Object],
8/15/2017 7:50:26 PM        _rp_resolve: [Function],
8/15/2017 7:50:26 PM        _rp_reject: [Function],
8/15/2017 7:50:26 PM        _rp_promise: [Object],
8/15/2017 7:50:26 PM        _rp_callbackOrig: undefined,
8/15/2017 7:50:26 PM        callback: [Function],
8/15/2017 7:50:26 PM        _rp_options: [Object],
8/15/2017 7:50:26 PM        setHeader: [Function],
8/15/2017 7:50:26 PM        hasHeader: [Function],
8/15/2017 7:50:26 PM        getHeader: [Function],
8/15/2017 7:50:26 PM        removeHeader: [Function],
8/15/2017 7:50:26 PM        localAddress: undefined,
8/15/2017 7:50:26 PM        pool: [Object],
8/15/2017 7:50:26 PM        dests: [],
8/15/2017 7:50:26 PM        __isRequestRequest: true,
8/15/2017 7:50:26 PM        _callback: [Function: RP$callback],
8/15/2017 7:50:26 PM        proxy: null,
8/15/2017 7:50:26 PM        tunnel: true,
8/15/2017 7:50:26 PM        setHost: true,
8/15/2017 7:50:26 PM        originalCookieHeader: undefined,
8/15/2017 7:50:26 PM        _disableCookies: true,
8/15/2017 7:50:26 PM        _jar: undefined,
8/15/2017 7:50:26 PM        port: 443,
8/15/2017 7:50:26 PM        host: 'api.wink.com',
8/15/2017 7:50:26 PM        path: '/oauth2/token',
8/15/2017 7:50:26 PM        _json: true,
8/15/2017 7:50:26 PM        httpModule: [Object],
8/15/2017 7:50:26 PM        agentClass: [Object],
8/15/2017 7:50:26 PM        agent: [Object],
8/15/2017 7:50:26 PM        _started: true,
8/15/2017 7:50:26 PM        href: 'https://api.wink.com/oauth2/token',
8/15/2017 7:50:26 PM        req: [Object],
8/15/2017 7:50:26 PM        ntick: true,
8/15/2017 7:50:26 PM        response: [Circular],
8/15/2017 7:50:26 PM        originalHost: 'api.wink.com',
8/15/2017 7:50:26 PM        originalHostHeaderName: 'host',
8/15/2017 7:50:26 PM        responseContent: [Circular],
8/15/2017 7:50:26 PM        _destdata: true,
8/15/2017 7:50:26 PM        _ended: true,
8/15/2017 7:50:26 PM        _callbackCalled: true },
8/15/2017 7:50:26 PM     toJSON: [Function: responseToJSON],
8/15/2017 7:50:26 PM     caseless: Caseless { dict: [Object] },
8/15/2017 7:50:26 PM     read: [Function],
8/15/2017 7:50:26 PM     body: { data: null, errors: [Array], pagination: {} } } }
```
Im the only one using those api keys so not sure how it got throttled...

**Comment by sibartlett** [comment] 2017-08-16 13:20
@bassrock I think I know why you're being throttled. It's not that you've performed too many requests, but rather: the plugin is making too many requests in a short period of time.

How many Wink hubs and relays do you have?

**Comment by bassrock** [comment] 2017-08-16 16:40
@sibartlett I have 4 Wink Relays and 1 Wink Hub 2. Maybe there should be a sleep between every 2 calls?

**Comment by sibartlett** [comment] 2017-08-16 19:29
@bassrock that's 5 hubs, so yeah - I'll add some throttling for the hub authentication requests. Will update here when that's done.

**Comment by sibartlett** [comment] 2017-08-16 23:13
@bassrock I've published a new version (1.5.7) which should hopefully fix your issue.

**Comment by smartymanav** [comment] 2017-08-16 23:25
Awesome @sibartlett , the issue is fixed for me atleast. Though I only have one hub. Maybe a co-incidence that it got fixed foe me as well...Thanks a lot though!

**Comment by dcgrove** [comment] 2017-08-17 00:05
So I am not sure if this is related, but after upgrading this plugin to the latest version, homebridge will no longer start.  My exact terminal session is below, and I have attached the log file after I tried to start homebridge and reinstall homebridge in documents.zip.

`npm update -g



`

[Documents.zip](https://github.com/sibartlett/homebridge-wink3/files/1229794/Documents.zip)

**Comment by sibartlett** [comment] 2017-08-17 00:51
@dcgrove running `npm update -g` will upgrade all globally installed packages.

Reading the log, I can see the error is occurring when upgrading homebridge itself - not this plugin.

Another user reported a similar issue back in May, they posted their solution [here](https://github.com/agnat/node_mdns/issues/192#issuecomment-301135749). I dunno if that would work for you?

**Comment by dcgrove** [comment] 2017-08-17 19:29
@sibartlett They fixed it by running xcode for Mac.  I am on Ubuntu so that's not gonna work for me.

**Comment by sibartlett** [comment] 2017-08-17 19:52
@dcgrove is your homebridge installation not working at all now? I would maybe try uninstalling rend re-installing homebridge if that's the case.

I also saw a similar mdns issue reported today in the homebridge slack: https://homebridgeteam.slack.com/archives/C0JN225EW/p1502979407000544

**Comment by sibartlett** [comment] 2017-08-17 21:01
I am closing this issue.

If anyone still has an issue they need assistance with, then please create a new issue.

**Closed by sibartlett** 2017-08-17 21:01 UTC
